package pbo_m14_5210411401;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

public class WorkerForm extends javax.swing.JFrame {
    
    private Connection db;
    private DefaultTableModel model;
    
     private void loadDataToTabel() {
        model.setRowCount(0);

        try {
            db = KoneksiDB.getKoneksi();
            Statement st = db.createStatement();

            String sql = "SELECT * FROM data_pegawai";

            ResultSet rs = st.executeQuery(sql);

            while(rs.next()) {
                Object[] data = new Object[5];
                data[0] = rs.getString("nama");
                data[1] = rs.getString("no_pegawai");
                data[2] = rs.getString("posisi");
                data[3] = rs.getString("gaji");
                data[4] = rs.getString("id_pegawai");

                model.addRow(data);
            }

            rs.close();
            st.close();
        }
        catch (SQLException e) {
            System.err.println("Load data eror: " + e.getMessage());
        }
    }
     
    private void initKomponenTambahan() {
        model = (DefaultTableModel) tabelPegawai.getModel();
        this.loadDataToTabel();
        txtGaji.setEditable(false);
    }

    public WorkerForm(String username) {
        initComponents();;
        db = KoneksiDB.getKoneksi();
        initKomponenTambahan();
    }
    public WorkerForm() {
        initComponents();
        tabelPegawai.getColumnModel().getColumn(4).setMinWidth(0);
        tabelPegawai.getColumnModel().getColumn(4).setMaxWidth(0);
        initKomponenTambahan();
        
        db = KoneksiDB.getKoneksi();
    }
    
    public void printall() throws NoPegawaiHarus10Digit, FieldTidakBolehKosong {
        String nope, nop, nama;        
        try {
            nama = (txtNama.getText());
            nop = (txtNoPegawai.getText());
        } catch (NullPointerException e) {
            throw new FieldTidakBolehKosong();
        }
        
        if (nama.equals("")) {
            throw new FieldTidakBolehKosong();
        } else if (nop.equals("")) {
            throw new FieldTidakBolehKosong();
        }
        
        try {
           nope = (txtNoPegawai.getText());
        } catch (StringIndexOutOfBoundsException e) {
            throw new NoPegawaiHarus10Digit();
        }
        
        if (nope.length() > 10) {
            throw new NoPegawaiHarus10Digit();
            
        }
        
        Pegawai pgw = new Pegawai (
                txtNama.getText(),
                txtNoPegawai.getText(),
                cmbPosisi.getSelectedItem().toString(),
                txtGaji.getText()
        );
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgProgramStudi = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtNoPegawai = new javax.swing.JTextField();
        cmbPosisi = new javax.swing.JComboBox<>();
        txtGaji = new javax.swing.JTextField();
        bttnInsert = new javax.swing.JButton();
        jSeparator = new javax.swing.JSeparator();
        bttnExit = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelPegawai = new javax.swing.JTable();
        bttnUpdt = new javax.swing.JButton();
        bttnDel = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("IT Worker Form");

        jLabel3.setText("Nama");

        jLabel4.setText("No. Pegawai");

        jLabel5.setText("Posisi");

        jLabel6.setText("Gaji");

        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });

        cmbPosisi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Posisi", "Senior Programmer", "Bussines Analyst", "Data Center Officer", "Junior Programmer" }));
        cmbPosisi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbPosisiMouseClicked(evt);
            }
        });
        cmbPosisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPosisiActionPerformed(evt);
            }
        });

        txtGaji.setBackground(new java.awt.Color(204, 204, 204));

        bttnInsert.setText("Insert");
        bttnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnInsertActionPerformed(evt);
            }
        });

        bttnExit.setText("Exit");
        bttnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnExitActionPerformed(evt);
            }
        });

        tabelPegawai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "No Pegawai", "Posisi", "Gaji", "ID Pegawai"
            }
        ));
        tabelPegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPegawaiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelPegawai);

        bttnUpdt.setText("Update");
        bttnUpdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnUpdtActionPerformed(evt);
            }
        });

        bttnDel.setText("Delete");
        bttnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnDelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bttnExit)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bttnInsert)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                                .addComponent(bttnUpdt))
                            .addComponent(txtNama)
                            .addComponent(txtNoPegawai)
                            .addComponent(txtGaji)
                            .addComponent(cmbPosisi, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(bttnDel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)))
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(bttnExit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNoPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(cmbPosisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtGaji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttnInsert)
                    .addComponent(bttnUpdt))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bttnDel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void bttnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnInsertActionPerformed
        
        try {
            db = KoneksiDB.getKoneksi();
            this.printall();

            String sql = "INSERT INTO data_pegawai"
                    + "(nama,no_pegawai,posisi,gaji)"
                    + "VALUES (?,?,?,?)";

            PreparedStatement ps = db.prepareStatement(sql);

            ps.setString(1, txtNama.getText());
            ps.setString(2, txtNoPegawai.getText());
            ps.setString(3, cmbPosisi.getSelectedItem().toString());
            ps.setString(4, txtGaji.getText());

            int rowInsert = ps.executeUpdate();
            if (rowInsert > 0) {
                JOptionPane.showMessageDialog(this, "Data berhasil disimpan", "Success", JOptionPane.INFORMATION_MESSAGE);
            }

            ps.close();
        }
        catch (SQLException e) {
            System.err.println("Insert data eror: " + e.getMessage());
        }
        catch (NoPegawaiHarus10Digit e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        } catch (FieldTidakBolehKosong e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            new WorkerForm().setVisible(true);
            this.dispose();
        }
        finally {
            // Load tabel mahasiswa untuk melihat perubahan
            this.loadDataToTabel();
        }
       
    
    }//GEN-LAST:event_bttnInsertActionPerformed

    private void bttnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_bttnExitActionPerformed

    private void tabelPegawaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPegawaiMouseClicked
        // TODO add your handling code here:
        int rowIdx = tabelPegawai.getSelectedRow();

        // Tampilkan data ke form
        String nama = tabelPegawai.getValueAt(rowIdx, 0).toString();
        txtNama.setText(nama);

        String no_pegawai = tabelPegawai.getValueAt(rowIdx, 1).toString();
        txtNoPegawai.setText(no_pegawai);

        String Posisi = tabelPegawai.getValueAt(rowIdx, 2).toString();
        switch (Posisi) {
            case "Senior Progammer":
                cmbPosisi.setSelectedIndex(1);
                txtGaji.setText("15.000.000");
                break;
            case "Bussines Analyst":
                cmbPosisi.setSelectedIndex(2);
                txtGaji.setText("21.000.000");
                break;
            case "Data Center Officer":
                cmbPosisi.setSelectedIndex(3);
                txtGaji.setText("18.000.000");
                break;
            default:
                cmbPosisi.setSelectedIndex(4);
                txtGaji.setText("8.000.000");
        }
        
        String gaji = tabelPegawai.getValueAt(rowIdx, 3).toString();
        txtGaji.setText(gaji);

    }//GEN-LAST:event_tabelPegawaiMouseClicked

    private void bttnUpdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnUpdtActionPerformed
        // TODO add your handling code here:
         try {
            db = KoneksiDB.getKoneksi();
            int rowIdx = tabelPegawai.getSelectedRow();

            String sql = "UPDATE data_pegawai "
                    + "SET nama=?, no_pegawai=?, posisi=?, gaji=? "
                    + "WHERE id_pegawai=?;";

            PreparedStatement ps = db.prepareStatement(sql);

            ps.setString(1, txtNama.getText());
            ps.setString(2, txtNoPegawai.getText());
            ps.setString(3, cmbPosisi.getSelectedItem().toString());
            ps.setString(4, txtGaji.getText());
            ps.setString(5, tabelPegawai.getValueAt(rowIdx, 4).toString());
            int rowInsert = ps.executeUpdate();
            if (rowInsert > 0) {
                JOptionPane.showMessageDialog(this, "Data berhasil diperbarui", "Success", JOptionPane.INFORMATION_MESSAGE);
            }

            ps.close();
        }
        catch (SQLException e) {
            System.err.println("Update data eror: " + e.getMessage());
        }
        finally {
            // Load tabel mahasiswa untuk melihat perubahan
            this.loadDataToTabel();
        }
    }//GEN-LAST:event_bttnUpdtActionPerformed

    private void bttnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnDelActionPerformed
        // TODO add your handling code here:
        try {
            db = KoneksiDB.getKoneksi();
            int rowIdx = tabelPegawai.getSelectedRow();

            String sql = "DELETE FROM data_pegawai "
                    + "WHERE id_pegawai=?;";

            PreparedStatement ps = db.prepareStatement(sql);
            
            ps.setString(1, tabelPegawai.getValueAt(rowIdx, 4).toString());


            int rowInsert = ps.executeUpdate();
            if (rowInsert > 0) {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Success", JOptionPane.INFORMATION_MESSAGE);
            }

            ps.close();
        }
        catch (SQLException e) {
            System.err.println("Delete data eror: " + e.getMessage());
        }
        finally {
            // Load tabel mahasiswa untuk melihat perubahan
            this.loadDataToTabel();
        }
    }//GEN-LAST:event_bttnDelActionPerformed

    private void cmbPosisiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbPosisiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPosisiMouseClicked

    private void cmbPosisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPosisiActionPerformed
        // TODO add your handling code here:
        switch (cmbPosisi.getSelectedItem().toString()) {
            case "Senior Programmer":
                txtGaji.setText("15.000.000");
                break;
            case "Bussines Analyst":
                txtGaji.setText("21.000.000");
                break;
            case "Data Center Officer":
                txtGaji.setText("18.000.000");
                break;
            case "Junior Programmer":
                txtGaji.setText("8.000.000");
                break;
            default:
                txtGaji.setText("");
                break;
                
        }
    }//GEN-LAST:event_cmbPosisiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WorkerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WorkerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WorkerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WorkerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WorkerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgProgramStudi;
    private javax.swing.JButton bttnDel;
    private javax.swing.JButton bttnExit;
    private javax.swing.JButton bttnInsert;
    private javax.swing.JButton bttnUpdt;
    private javax.swing.JComboBox<String> cmbPosisi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tabelPegawai;
    private javax.swing.JTextField txtGaji;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNoPegawai;
    // End of variables declaration//GEN-END:variables
}
